scheduler/urls.py
from django.urls import path

from . import views

app_name = "scheduler"

urlpatterns = [
    path('', views.index, name='index'),
    path("makeorg", views.makeorg, name="makeorg"),
    path("makeuser",views.makeuser,name="makeuser"),
    path("join", views.joinorg, name="joinorg"),
]

univScraping/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("scheduler.urls")),
    path('admin/', admin.site.urls),
]

scheduler/models.py
from django.db import models


class Org(models.Model):
    team_id      = models.CharField(max_length=256, primary_key=True)
    team_pre     = models.CharField(max_length=256,null=True)
    team_aft     = models.CharField(max_length=256,null=True)
    #name =  models.CharField(max_length=30)
    """
    def get_absolute_url(self):
        return reverse('team-detail', args=[str(self.id_team)])
    
    def __str__(self):
        return self.team_id
    """

class User(models.Model):
    student_id   = models.CharField(max_length=256, primary_key=True)    
    #name= models.CharField(max_length=256,null=True)
    team   = models.ForeignKey("Org", to_field="team_id", on_delete=models.SET_NULL, null=True)
    qtr_pre      = models.IntegerField(default=0) # 前期講義日程(合計） 
    qtr_aft      = models.IntegerField(default=0) # 後期講義日程(合計)
    
    """
    def get_absolute_url(self):
        return reverse('member-detail', args=[str(self.student_id)])
    
    def __str__(self):
        return self.org
    """

scheduler/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .scraping import getPageSource, getTime, exportAsDict, makeList, changeData, beRowData
from scheduler.models import  User, Org
from d2b import d2b,make_countlist,makeOrg,makedata

def index(request):
    #indexを読み込んでデフォルトの画面表示
    return render(request, "scheduler/index.html")


def makeuser(request):
    if request.method == 'POST':
        # ユーザー登録に必要なデータ軍の定義
        id = request.POST["school_number"]
        pswd       = request.POST["password"]
        
        # ユーザーの講義データを取得
        html      = getPageSource(id, pswd)
        dict_data = exportAsDict(html)
        dict_data = dict_data['Spring']
        pre_class, aft_class = changeData(dict_data)

        # 講義データのバイナリ変換
        pre_class = beRowData(pre_class)
        aft_class = beRowData(aft_class)

        # 書き出しサイズがオーバーフローを起こすため10進数に変換して書き込む
        db_user = User(
            student_id = id,
            team = None,
            qtr_pre = int(pre_class, 2),
            qtr_aft = int(aft_class, 2),
        )
        db_user.save()
    return render(request, "scheduler/makeuser.html")


def makeorg(request):#チームID作成
    if request.method == 'POST':
        team_id = request.POST["team_id"] # 任意のteam_id
        init_data=makedata()
        db_org = Org(team_id=team_id,team_pre =init_data ,team_aft=init_data)
        db_org.save()

    return render(request, "scheduler/makeorg.html")


def joinorg(request):
    if request.method == 'POST':
        #if request.filter(Org.objects.get("team_id").exists()):
        #    print("ok")
        #id = request.POST["school_number"]
        #print(mode_data.qtr_pre)
        team_id_post = request.POST["team_id"] # 参加するチームのteam_idのOrgオブジェクト
        team_id_org = Org.objects.get(team_id=team_id_post)

        Org_predata=team_id_org.team_pre
        Org_aftdata=team_id_org.team_aft


        school_number_post =request.POST["school_number"]#ユーザのオブジェクト作成
        school_number_user=User.objects.get(student_id=school_number_post)
        user_predata=d2b(school_number_user.qtr_pre)
        user_aftdata=d2b(school_number_user.qtr_aft)

        #####更新#####
       
        """
        db_usr = User(team_id=team_id_org,team_pre = 1,team_aft= 1)#Database更新
        db_usr.save()
        """
    return render(request, "scheduler/join.html")

scheduler/templates/scheduler/index.html
{% extends "base.html" %}
{% block title %}scheduler{% endblock title %}
{% block content %}
<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Monday   </th>
      <th scope="col">Tuesday  </th>
      <th scope="col">Wednesday</th>
      <th scope="col">Thursday </th>
      <th scope="col">Friday   </th>
      <th scope="col">Saturday </th>
      <th scope="col">Sunday   </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">5</th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">6</th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>
{% endblock %}

scheduler/templates/scheduler/join.html
{% extends "base.html" %}
{% block title %}だんたいとうろくふぉーむ{% endblock title %}
{% block content %}
<form method="POST" action="{% url 'scheduler:joinorg' %}">
  {% csrf_token %}
  <div class="form-group">
    <label for="team_id">Team ID</label>
    <input type="text" class="form-control" name="team_id" placeholder="Input team id you want to join.">
  </div>

  <div>
    <label for="display_name">学籍番号</label>
      <input type="text" class="form-control" name="school_number" placeholder="display name">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

scheduler/templates/scheduler/makeorg.html
{% extends "base.html" %}
{% block title %}だんたいとうろくふぉーむ{% endblock title %}
{% block content %}
<form method="POST" action="{% url 'scheduler:makeorg' %}" class="all">
  {% csrf_token %}
  <div class="form-group">
    <div class="mx-auto" style="width: 200px;">
    <label>TEAM ID
      <input type="text" size="20" class="form-control" name="team_id" placeholder="custom team id">
    </label>
    <br>
    <button type="submit" class="btn btn-primary">SUBMIT</button>
    </div>
  </div>
</form>
{% endblock %}

scheduler/templates/scheduler/makeuser.html
{% extends "base.html" %}
{% block title %}だんたいとうろくふぉーむ{% endblock title %}
{% block content %}
<form method="POST" action="{% url 'scheduler:makeuser' %}">
  {% csrf_token %}
  <div>
    <label for="display_name">学籍番号</label>
      <input type="text" class="form-control" name="school_number" placeholder="display name">
  </div>
  <div>
    <label for="password">password</label>
      <input type="text" class="form-control" name="password" placeholder="display name">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

scheduler/templates/scheduler/test.html
{% extends "base.html" %}
{% block title %}てすとふぉーむ{% endblock title %}
{% block content %}
<form method="POST" action="{%url 'scheduler:execute'%}">
  {% csrf_token %}
  <div class="form-group">
    <div class="mx-auto" style="width: 200px;">
    <label>Org ID
      <input type="text" size="20" class="form-control" name="team_id" placeholder="custom team id">
    </label>
    <br>
    <label>Student ID
      <input type="text" size="20" class="form-control" name="student_id" placeholder="student id">
    </label>
    <label>Password (ToyoNet-G)
      <input type="password" size="20" class="form-control" name="password">
    </label>
    <label>Display Name
      <input type="text" size="20" class="form-control" name="display_name" placeholder="custom display name">
    </label>
    <label>User Name
      <input type="text" size="20" class="form-control" name="username" placeholder="custom display name">
    </label>
    <br>
    <button type="submit" class="btn btn-primary">SUBMIT</button>
    </div>
  </div>
</form>
{% endblock %}

templates/base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="full" %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    {% block extra_css %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">すけじゅーらー</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'scheduler:makeuser' %}">ユーザ登録</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'scheduler:makeorg' %}">作成</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'scheduler:joinorg' %}">参加</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'scheduler:index' %}">一覧</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    {% block extra_js %}{% endblock %}
  </body>
</html>